---
name: jawaaplicacion
description: jawa
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  loading: ^1.0.2
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  image_picker: ^0.6.7+12
  firebase_storage: ^4.0.1
  provider: ^4.3.2+2
  get_it: ^5.0.1
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.0
  geoflutterfire: ^2.2.1
  flutter_swiper: ^1.1.6
  shared_preferences: ^0.5.12+2
  firebase_core: ^0.5.0+1
  uuid: ^2.2.2
  app_settings: ^4.0.4
  after_layout: ^1.0.7+2
  url_launcher: ^5.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: "assets/images/logo.png" 
   
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/demo/
